page_title: Lightmatter Workflow Dashboard
copier_project: lincc-frameworks/python-project-template

repos:
  - repo: sofware-qa
    owner: lightmatter-ai
    other_workflows:
      - OpenBMC Build + Deploy + Robot Tests 
  - repo: openbmc
    owner: lightmatter-ai
    branch: master  
    live-build: CI.yml
    smoke-test: main.yml
  - repo: passage-ops
    owner: lightmatter-ai
    branch: main
    smoke-test: build-test-remote.yml
    live-build: build-test.yml
  - repo: laser-ops  
    owner: lightmatter-ai
    live-build: build-test.yml
  - repo: serdes
    owner: lightmatter-ai
    smoke-test: build-test-remote.yml
    live-build: build-test.yml
    docs-build: generate-and-publish-documentation.yml
  - repo: masai-sdk
    owner: lightmatter-ai
    smoke-test: bmc-integration-tests.yml
    live-build: ci.yml
    docs: deploy-docs.yml
  - repo: FPGA_OS
    owner: lightmatter-ai
 
